WITH V AS
  (SELECT FVNH.FLEX_VALUE_SET_ID,
    FVNH.PARENT_FLEX_VALUE,
    FVNH.RANGE_ATTRIBUTE,
    FVNH.CHILD_FLEX_VALUE_LOW,
    FVNH.CHILD_FLEX_VALUE_HIGH,
    FVNH.LAST_UPDATE_DATE,
    FVNH.LAST_UPDATED_BY,
    FVNH.CREATION_DATE,
    FVNH.CREATED_BY,
    FVNH.LAST_UPDATE_LOGIN,
    FVNH.START_DATE_ACTIVE,
    FVNH.END_DATE_ACTIVE,
    FVS.FLEX_VALUE_SET_NAME
  FROM FND_FLEX_VALUE_NORM_HIERARCHY FVNH ,
    FND_FLEX_VALUE_SETS FVS
  WHERE FVS.FLEX_VALUE_SET_ID  =FVNH.FLEX_VALUE_SET_ID
  AND (FVNH.PARENT_FLEX_VALUE <> 'T'
  AND FVS.FLEX_VALUE_SET_NAME LIKE 'XXAQV_GL_COA%')
  ) ,
  V2 AS
  (SELECT LEVEL LEVEL_NUM,
    FVNH.FLEX_VALUE_SET_ID,
    FVNH.FLEX_VALUE_SET_NAME,
    FVNH.PARENT_FLEX_VALUE,
    FVNH.RANGE_ATTRIBUTE,
    FVNH.CHILD_FLEX_VALUE_LOW,
    FVNH.CHILD_FLEX_VALUE_HIGH,
    FVNH.LAST_UPDATE_DATE,
    FVNH.LAST_UPDATED_BY,
    FVNH.CREATION_DATE,
    FVNH.CREATED_BY,
    FVNH.LAST_UPDATE_LOGIN,
    FVNH.START_DATE_ACTIVE,
    FVNH.END_DATE_ACTIVE
  FROM V FVNH
    START WITH FVNH.RANGE_ATTRIBUTE        ='C'
    CONNECT BY PRIOR FVNH.FLEX_VALUE_SET_ID=FVNH.FLEX_VALUE_SET_ID
  AND PRIOR FVNH.PARENT_FLEX_VALUE BETWEEN FVNH.CHILD_FLEX_VALUE_LOW AND FVNH.CHILD_FLEX_VALUE_HIGH
  AND FVNH.RANGE_ATTRIBUTE          ='P'
  AND PRIOR FVNH.PARENT_FLEX_VALUE <> FVNH.PARENT_FLEX_VALUE
  ) ,
  V3 AS
  (SELECT FND_FLEX_VALUE_SETS.FLEX_VALUE_SET_ID,
    FND_FLEX_VALUE_SETS.FLEX_VALUE_SET_NAME,
    FND_FLEX_VALUES.FLEX_VALUE_ID ,
    FND_FLEX_VALUES.FLEX_VALUE ,
    FND_FLEX_VALUES_TL.DESCRIPTION
  FROM FND_FLEX_VALUES,
    FND_FLEX_VALUE_SETS,
    FND_FLEX_VALUES_TL
  WHERE FND_FLEX_VALUES.FLEX_VALUE_SET_ID = FND_FLEX_VALUE_SETS.FLEX_VALUE_SET_ID
  AND FND_FLEX_VALUES.FLEX_VALUE_ID       = FND_FLEX_VALUES_TL.FLEX_VALUE_ID
  AND FND_FLEX_VALUES_TL.LANGUAGE         = 'US'
  AND ( FND_FLEX_VALUES.FLEX_VALUE       <> 'T'
  AND FND_FLEX_VALUE_SETS.FLEX_VALUE_SET_NAME LIKE 'XXAQV_GL_COA%')
  )
SELECT V3.FLEX_VALUE_SET_NAME,
  V3.FLEX_VALUE,
  V3.DESCRIPTION
FROM V3
LEFT OUTER JOIN V2
ON V2.FLEX_VALUE_SET_ID = V3.FLEX_VALUE_SET_ID
AND V3.FLEX_VALUE BETWEEN V2.CHILD_FLEX_VALUE_LOW AND V2.CHILD_FLEX_VALUE_HIGH
AND V2.LEVEL_NUM=1
WHERE V3.FLEX_VALUE_SET_NAME
  ||'~'
  ||V3.FLEX_VALUE NOT IN
  (SELECT P.FLEX_VALUE_SET_NAME||'~'||P.PARENT_FLEX_VALUE FROM V2 P
  )
AND v2.FLEX_VALUE_SET_NAME IS NULL
ORDER BY 1,2
